In [19]:
import pandas as pd
import numpy as np

In [20]:
df=pd.read_csv('IMDB Dataset.csv')

In [21]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [22]:
# One review
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

## Text Cleaning

1. Sample 10000 rows
2. Remove html tags
3. Remove special characters
4. Converting every thing to lower case
5. Removing Stop words
6. Stemming

In [23]:
df=df.sample(10000)

In [24]:
df.shape

(10000, 2)

In [25]:
df.info()

<class 'pandas.DataFrame'>
Index: 10000 entries, 40595 to 46084
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  str
 1   sentiment  10000 non-null  str
dtypes: str(2)
memory usage: 234.4 KB

In [26]:
df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

C:\Users\rudra\AppData\Local\Temp\ipykernel_13524\4240984564.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

40595    0
49311    0
28957    1
27073    0
32958    1
        ..
20161    0
10339    1
23193    1
1326     0
46084    0
Name: sentiment, Length: 10000, dtype: object

In [27]:
df.head()

                                                  review sentiment
40595  Crazy director....Yeah, you need to be crazy t...  negative
49311  I don't know much about film-making, but good ...  negative
28957  In a bizarre experiment, an astronaut is aband...  positive
27073  For producer David O. Selznick, no one directo...  negative
32958  After all these years, of Peter O'Tool's brill...  positive

In [28]:
import re
clean = re.compile('<.*?>')
re.sub(clean, '', df.iloc[2].review)

'In a bizarre experiment, an astronaut is abandoned on the moon as Alice (Florinda Bolkan), a troubled translator living in Italy, wakes from a nightmare about a lunar mission mixed with an old movie that frightened her as a child. She also has no recollection of the last three days except for a torn photo of the Garma hotel she finds in her apartment. Fired from her job, Alice heads to that resort island to try and piece together the mystery...Often touted as a giallo due to it\'s director (THE FIFTH CORD\'s Luigi Bazzoni) and the presence of Evelyn Stewart, Nicoletta Elmi, and Klaus Kinski, FOOTPRINTS is actually a deliberately paced psycho-thriller with sci-fi overtones. Blurring the distinction between dream, reality, memory and movies, the disturbing story is beautifully photographed by Oscar-winner Vittorio Storaro with a pensive score by Nicola Piovani. It also combines elements of such diverse films as Armando Crispino\'s MACCHE SOLARI and Lucino Visconti\'s DEATH IN VENICE in it\'s depiction of alienation, isolation, hallucination, and maybe madness. Brazilian actress Florinda Bolkan, on screen all the time, does a redux of her Carol Hammond in Lucio Fulci\'s A LIZARD IN A WOMAN\'S SKIN as Alice, a young woman thrust into a mystery that makes her question her sanity. The locations mirror Alice\'s unstable state of mind; the island of Garma, off-season, with it\'s Arabic influence and ancient ruins, is a lonely, almost mystical place unwilling to give up its secrets. Evelyn Stewart has a bit in the beginning as a concerned friend, Nicoletta Elmi and Oscar-winner Lila Kedrova are hotel guests, Peter McEnery plays a handsome biologist trying to help Bolkan, and the ever-intense Klaus Kinski is "Blackmann" in the film-within-a-film, "Footprints On The Moon". FOOTPRINTS is a classy case of "Guaranteed 100% Euro-weird" but not for everyone. There\'s only one murder toward the end but you won\'t see it coming as the film starts to come together.'

In [29]:
# Function to clean html tags
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [30]:
df['review']=df['review'].apply(clean_html)

In [31]:
# converting everything to lower

def convert_lower(text):
    return text.lower()

In [32]:
df['review']=df['review'].apply(convert_lower)

In [33]:
# function to remove special characters

def remove_special(text):
    x=''
    
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x + ' '
    return x

In [34]:
remove_special(' th%e @ classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare. forget pretty pictures painted for mainstream audiences, f')

' th e   classic use of the word it is called oz as that is the nickname given to the oswald maximum security state penitentary  it focuses mainly on emerald city  an experimental section of the prison where all the cells have glass fronts and face inwards  so privacy is not high on the agenda  em city is home to many  aryans  muslims  gangstas  latinos  christians  italians  irish and more    so scuffles  death stares  dodgy dealings and shady agreements are never far away i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare  forget pretty pictures painted for mainstream audiences  f'

In [35]:
df['review']=df['review'].apply(remove_special)

In [36]:
# Remove the stop words
import nltk

In [37]:
from nltk.corpus import stopwords

In [38]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [39]:
df

                                                  review sentiment
40595  crazy director    yeah  you need to be crazy t...  negative
49311  i don t know much about film making  but good ...  negative
28957  in a bizarre experiment  an astronaut is aband...  positive
27073  for producer david o  selznick  no one directo...  negative
32958  after all these years  of peter o tool s brill...  positive
...                                                  ...       ...
20161  after seeing the 1996 remake  i thought it was...  negative
10339  ok  i saw this in the theaters when it came ou...  positive
23193  from a military historian s standpoint  nearly...  positive
1326   teenage exorcist is one of those god awful fil...  negative
46084  for the most part  on demand delivers some pre...  negative

[10000 rows x 2 columns]

In [40]:

def remove_stopwords(text):
    x=[]
    for i in text.split():
        
        if i not in stopwords.words('english'):
            x.append(i)
    y=x[:]
    x.clear()
    return y

In [ ]:
df['review']=df['review'].apply(remove_stopwords)

In [ ]:
df

                                                  review  sentiment
24181  [awhile, hooked, shows, like, ghost, hunters, ...          0
33972  [man, gaston, modot, young, girl, lya, lys, go...          0
36735  [completely, agree, review, watched, movie, 5,...          0
7272   [take, makes, use, familiar, plot, fine, perfo...          1
42497  [norwegian, film, starts, man, jumping, subway...          1
...                                                  ...        ...
37487  [ok, american, humble, scottish, opinion, stev...          0
7582   [movie, made, feel, missed, important, scenes,...          0
17748  [beware, spoilers, movie, okay, goldie, hawn, ...          1
24281  [remembered, awful, movie, bought, camelot, mu...          0
29109  [must, little, skeptical, entered, cinema, wat...          1

[10000 rows x 2 columns]

In [ ]:
# Perform stemming

from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [ ]:
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z

In [ ]:
stem_words(['I','loved','loving','it'])

['I', 'love', 'love', 'it']

In [ ]:
df['review']=df['review'].apply(stem_words)

In [ ]:
df

                                                  review  sentiment
24181  [awhil, hook, show, like, ghost, hunter, desti...          0
33972  [man, gaston, modot, young, girl, lya, ly, go,...          0
36735  [complet, agre, review, watch, movi, 5, minut,...          0
7272   [take, make, use, familiar, plot, fine, perfor...          1
42497  [norwegian, film, start, man, jump, subway, ap...          1
...                                                  ...        ...
37487  [ok, american, humbl, scottish, opinion, steve...          0
7582   [movi, made, feel, miss, import, scene, begin,...          0
17748  [bewar, spoiler, movi, okay, goldi, hawn, chri...          1
24281  [rememb, aw, movi, bought, camelot, music, sto...          0
29109  [must, littl, skeptic, enter, cinema, watch, o...          1

[10000 rows x 2 columns]

In [ ]:
# Join back

def join_back(list_input):
    return " ".join(list_input)

In [ ]:
df['review']=df['review'].apply(join_back)

In [ ]:
df['review']

24181    awhil hook show like ghost hunter destin truth...
33972    man gaston modot young girl lya ly go film con...
36735    complet agre review watch movi 5 minut look on...
7272     take make use familiar plot fine perform genui...
42497    norwegian film start man jump subway appar com...
                               ...
37487    ok american humbl scottish opinion steve marti...
7582     movi made feel miss import scene begin continu...
17748    bewar spoiler movi okay goldi hawn chri sarand...
24281    rememb aw movi bought camelot music store summ...
29109    must littl skeptic enter cinema watch oss117 f...
Name: review, Length: 10000, dtype: object

In [ ]:
X=df.iloc[:,0:1].values

In [ ]:
X.shape

(10000, 1)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500)

In [ ]:
X=cv.fit_transform(df['review']).toarray()

In [ ]:
X.shape

(10000, 2500)

In [ ]:
X[0].mean()

0.1132

In [ ]:
y=df.iloc[:,-1].values

In [ ]:
y.shape

(10000,)

In [ ]:
# X,y
# Training set
# Test Set(Already know the result)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [ ]:
X_train.shape

(8000, 2500)

In [ ]:
X_test.shape

(2000, 2500)

In [ ]:
y_train.shape

(8000,)

In [ ]:
y_test.shape

(2000,)

In [ ]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [ ]:
clf1=GaussianNB()
clf2=MultinomialNB()
clf3=BernoulliNB()

In [ ]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [ ]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)
y_pred3=clf3.predict(X_test)

In [ ]:
y_test.shape

(2000,)

In [ ]:
y_pred1.shape

(2000,)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
print("Gaussian",accuracy_score(y_test,y_pred1))
print("Multinomial",accuracy_score(y_test,y_pred2))
print("Bernaulli",accuracy_score(y_test,y_pred3))

Gaussian 0.7185
Multinomial 0.8295
Bernaulli 0.835